### PR TITLE
Adding in nix and nix-bazel zoom backgrounds

### PR DESCRIPTION
**Pull request by pl-misuw**
Hey,

Just wanted to chime in with zoom-backgrounds.

### CODE REVIEW

**Comment by gytis-ivaskevicius** [comment]
What are these zoom backgrounds supposed to be? I don't think that I am a found of them.

**Comment by DieracDelta** [comment]
LGTM :+1:

**Review by DieracDelta — APPROVED** [review]

**Comment by max-privatevoid** [comment]
LGTM

**Comment by MatthewCroughan** [comment]
LGTM, love this.

**Comment by gytis-ivaskevicius** [comment]
Okay, i approve as long as there is some better folder and one of them (since they seem to be the same????). Maybe folder name should be `other`? 
Also video titles should be more verbose

**Comment by zachcoyle** [comment]
The logos are centered, so won't really be visible in most calls...

**Comment by pl-misuw** [comment]
Hey, sorry guys was a tad preoccupied!
As for logos yeah they are kinda in the middle, they make a nice angel-like aureola over you when using.

They are not the same, one has a bazel logo in it, but now that I think about it - this might be deleted. 
As for dirs and names, I'll change things around hopefully this evening! Sorry for the trouble.

**Comment by gytis-ivaskevicius** [comment]
whatever

**Pull request merged**
